### ISSUE TITLE
The metrics API in open5gs

### ISSUE THREAD

**Issue by myonlystarWang** [s5uishida/open5gs_5gc_ueransim_metrics_sample_config#3]
Hi @s5uishida 
    Thanks for this configuration introduction,it is so great!
    I would like to know if I want to use my own web page instead of `Grafana `,how should I get the API of metrics?
    Are they like the following?
    `http://192.168.0.111:9091/metrics/......`
    Is there some API list so I can retrieve it?
    Thanks in advance!

**Comment by s5uishida** [comment]
Hi @myonlystarWang 

I'm not familiar with it, but could you please use the following as a reference, or inquire about it in Open5GS Discussion?

https://prometheus.io/docs/prometheus/latest/querying/api/

**Comment by myonlystarWang** [comment]
@s5uishida Thank you very much for sharing this!
I'll take the time to build an `open5gs`+`prometheus `environment, and if I find the API for it, I'll share it here!

**Comment by myonlystarWang** [comment]
I think I can close this issue now,Thank you again!

**Comment by myonlystarWang** [comment]
Hi,
    Sorry to bother you again
    I am using v2.6.1(the latest) with apt install，and make sure the metrics is configured in the amf.yaml as below:
```
  metrics:
      - addr: 127.0.0.5
        port: 9090
```
   But there is no 9090 information with `netstat -tulpn`
   And run `curl http://127.0.0.5:9090/metrics` with connection refused.
   Perhaps this feature is not yet supported in v2.6.1(package install)?
   Thanks for advance!

**Comment by s5uishida** [comment]
@myonlystarWang 

I have built v2.6.1 and can see the metrics for AMF/PCF/SMF/UPF in my this repository scenario.

**Comment by myonlystarWang** [comment]
> 

Thanks for response!
So you compiled it from the source code? 
Then just keep the metrics configration in yaml, then can get metrics for AMF by `curl http://127.0.0.5:9090/metrics` right?

**Comment by s5uishida** [comment]
@myonlystarWang 

> So you compiled it from the source code?

Yes.

**Comment by myonlystarWang** [comment]
Thanks for your confirmation, I think `prometheus metrics` may not be turned on by default in the packaged version.
The issue should be closed.
